# Generated by Django 6.0.2 on 2026-03-10 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(help_text='O preço não pode ser negativo.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
