# Generated by Django 6.0.2 on 2026-03-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
    ]
