# Generated by Django 6.0.2 on 2026-03-22 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0006_remove_fornecedor_produtos'),
        ('produtos', '0005_remove_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='fornecedores.fornecedor'),
        ),
    ]
