# Generated by Django 6.0.2 on 2026-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_estado'),
        ('produtos', '0003_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='fornecedores', to='produtos.produto'),
        ),
    ]
