# Generated by Django 6.0.2 on 2026-03-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_fornecedor_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='produtos',
        ),
    ]
