# Generated by Django 6.0.2 on 2026-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_remove_fornecedor_produtos'),
        ('produtos', '0005_remove_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='fornecedores', to='produtos.produto'),
        ),
    ]
