# Generated by Django 6.0.2 on 2026-03-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0005_fornecedor_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='produtos',
        ),
    ]
